K01-insecure-workload-config [Add CPU Resource Constraints]
OWASP/www-project-kubernetes-top-ten pull request #55
Opened 2024-01-31 11:56 UTC by nigeldouglas-itcarlow

The 2023 Cloud-Native Security & Usage Report highlighted how 59% of containers running in Kubernetes has no CPU limits, and 49% of containers had no memory limits enforced. That's why I suggested resource constraints as a clear example of insecure workload configuration.

2024-01-31 14:02 UTC, szh requested changes
Thank you for the contribution, overall this is great. There are a few lint errors:

> 2022/en/src/K01-insecure-workload-configurations.md:90 MD031/blanks-around-fences Fenced code blocks should be surrounded by blank lines [Context: "```"]
2022/en/src/K01-insecure-workload-configurations.md:91:121 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
2022/en/src/K01-insecure-workload-configurations.md:91:81 MD013/line-length Line length [Expected: 80; Actual: 121]
2022/en/src/K01-insecure-workload-configurations.md:92:120 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
2022/en/src/K01-insecure-workload-configurations.md:92:81 MD013/line-length Line length [Expected: 80; Actual: 120]
2022/en/src/K01-insecure-workload-configurations.md:93:1[19](https://github.com/OWASP/www-project-kubernetes-top-ten/actions/runs/7725637475/job/21065114413?pr=55#step:5:20) MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
[20](https://github.com/OWASP/www-project-kubernetes-top-ten/actions/runs/7725637475/job/21065114413?pr=55#step:5:21)22/en/src/K01-insecure-workload-configurations.md:93:81 MD013/line-length Line length [Expected: 80; Actual: 119]
2022/en/src/K01-insecure-workload-configurations.md:94:114 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
20[22](https://github.com/OWASP/www-project-kubernetes-top-ten/actions/runs/7725637475/job/21065114413?pr=55#step:5:23)/en/src/K01-insecure-workload-configurations.md:94:81 MD013/line-length Line length [Expected: 80; Actual: 114]
2022/en/src/K01-insecure-workload-configurations.md:127:78 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
2022/en/src/K01-insecure-workload-configurations.md:128:31 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]

Additionally, "container" and "node" should be all lowercase. Once these are fixed this looks great to me.

2024-02-04 20:11 UTC, nigeldouglas-itcarlow commented
@szh Fixed linting errors and addressed the case sensitivity issue with container and node.

2024-02-05 14:33 UTC, szh requested changes
Looks good, thanks. Just a few more lint errors:

2022/en/src/K01-insecure-workload-configurations.md:92:81 MD013/line-length Line length [Expected: 80; Actual: 539]
2022/en/src/K01-insecure-workload-configurations.md:122:81 MD013/line-length Line length [Expected: 80; Actual: 111]
2022/en/src/K01-insecure-workload-configurations.md:123:106 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
2022/en/src/K01-insecure-workload-configurations.md:123:81 MD013/line-length Line length [Expected: 80; Actual: 106]

2024-02-05 22:16 UTC, nigeldouglas-itcarlow commented
All checks have finally passed. We should be good now, @szh . Thank you!

2024-02-06 14:16 UTC, szh approved these changes

2024-02-06 14:16 UTC, merged